### ISSUE TITLE
"clear text fields and set logo to default" does not work

### ISSUE THREAD

**Issue by foggydude** [noeal-dac/Animated-Lower-Thirds#13]
**Describe the bug**
All works as expected, but
- i can add title and subtitles to the memory slots of each of the 4 instances
- But once added, they cannot be changed or deleted.
- when button "clear text fields"pressed, the memory slots get greyed out and title and subtitle can be changed,
- but as soon as a memory slot number is clicked, it all (all slots) get restored to the first entered name. so all slots are filled with the same name and subtitle

- i have made sure all files have read/write access, further i have no idea where the entered fields get stored 

**Desktop (please complete the following information):**
 - OS: win 
 - OBS version -= latest = 26.1.1
 - Version [e.g. 22] = latest

**Additional context**

**Comment by noeal-dac** [comment]
Hi @foggydude!

I think you are understanding it from another point of view.

When you click on an empty slot you copy the content of the fields (name, info and logo) within it. When the slot has something saved, it will always load its content in the text fields when you click it.

If you want to save something new in an occupied slot, you must first empty it by **holding the click** until it flashes red. **The "clear text fields" button doesn't delete the content of the slots**, but the loaded content.

To know what content you have loaded, the slots are marked in white when their content is the same as the name, info and logo fields.

**This user has made a very simple tutorial:** [https://www.youtube.com/watch?v=0xcFX9I6uJc](https://www.youtube.com/watch?v=0xcFX9I6uJc)

I hope this helps you!

**Comment by foggydude** [comment]
oh man i feel dumb now. it works like a charm!

thanks a lot for the great work

One other issue: every time i select a logo, it makes me select the image but as soon i choose save, it shows the broken image sign. do i do something wrong (location/type/size)

**Comment by noeal-dac** [comment]
Make sure to copy the logos files in the Logos folder.
