### ISSUE TITLE
Not adding a logo

### ISSUE THREAD

**Issue by Macleopard** [noeal-dac/Animated-Lower-Thirds#18]
When i am choosing logo from another dir, it doesn't display correctly
Attached an youtube video
https://youtu.be/CE3Nqo0x7EY

**Comment by DavidP-B** [comment]
Hi! You should follow the steps configuration step by step. You must use the custom logo folder in order to work properly. It doesn't work with other folders, sorry. So, if you want to use yo it logos, you mist copy them into app logo folder. 

Thanks for use it!

**Comment by Macleopard** [comment]
And i can't add logo from another dir? Only from one

**Comment by DavidP-B** [comment]
Copy all the logos you want to use in the correct folder, that's the way 😉

**Comment by Macleopard** [comment]
Thank you for the information
