### ISSUE TITLE
Unable to insert logo

### ISSUE THREAD

**Issue by frazer81** [noeal-dac/Animated-Lower-Thirds#2]
Great work on this plug in, very simple to get going.
I cant seem to insert a logo - have tried PNG/TIFF/JPEG all with the same result.
Each time I select one, it shows the file missing icon - i'm selecting a file from a local folder (not network)
Have I configured something incorrectly, do they need to be copied to a specific location?

**Comment by noeal-dac** [comment]
Hi, make sure to copy the logos into the "logos" folder.
