### ISSUE TITLE
Alignment Issue on Design 2

### ISSUE THREAD

**Issue by skjall** [noeal-dac/Animated-Lower-Thirds#4]
In Design 2, with the same settings, the first and second line of LT1 is not at the same height as on the other LTs. For demonstration I put it both on left side. But it is the same on Left/Right or any other orientation.
LT2, LT3 and LT4 are perfectly aligned.
Design 1 and 3 are also fine.

Version 1.6 (latest)

![image](https://user-images.githubusercontent.com/13360352/106383667-8ec74d80-63c7-11eb-8120-52000ce2c98d.png)
![image](https://user-images.githubusercontent.com/13360352/106383681-97b81f00-63c7-11eb-9943-7c541fa62422.png)

`{"alt-2-style-color-2":"rgba(59,59,59,0)","alt-1-inverse-ratio":"8","alt-3-border-thickness":"false","lower-thirds-switch2":"true","alt-4-inverse-ratio":"8","alt-4-autoload":"false","alt-1-style":"2","alt-1-logo-default":"../logos/logo_1.png","alt-4-style-color-1":"rgba(213,65,65,0)","alt-2-align-left":"true","alt-1-preview":"false","alt-4-margin-h":"22","alt-1-style-color-1":"#E76000","alt-1-logo-2":"","alt-1-margin-v":"1","alt-3-margin-v":"1","alt-1-info-weight":"false","alt-3-style-color-1":"rgba(213,65,65,0)","set-tooltips":"false","alt-2-logo-preview":"../logos/logo_2.png","alt-1-shadow-amount":"5","alt-1-border-color":"false","alt-4-name-color":"#F2F2F2","alt-3-logo":"false","alt-2-align-right":"false","global-animation-time":"","alt-1-info-transform":"false","alt-2-logo":"false","alt-1-margin-h":"22","alt-1-lock-active":"true","alt-1-name-1":"","alt-1-active-time":"","alt-3-lock-active":"true","alt-1-logo-1":"","alt-1-inactive-time":"","alt-4-logo-preview":"../logos/logo_4.png","alt-4-style":"2","set-preview":"false","alt-1-name":"John Doe","alt-2-autotrigger":"false","alt-3-margin-h":"22","alt-1-style-color-3":"#E76000","alt-3-info":"","alt-3-name":"","alt-2-line-spacing":"1","alt-1-align-right":"false","alt-1-font":"'Open Sans', sans-serif","global-active-time":"15","alt-1-name-weight":"true","alt-2-info-color":"#F2F2F2","alt-1-logo-preview":"../logos/logo_1.png","set-slot-numbers":"false","alt-3-border-color":"false","lower-thirds-masterswitch":"true","alt-4-line-spacing":"1","alt-2-style-color-3":"#E76000","alt-3-info-color":"#F2F2F2","alt-3-logo-preview":"../logos/logo_1.png","lower-thirds-switch1":"true","alt-2-inverse-ratio":"8","alt-1-corners":"0","alt-1-logo":"false","alt-2-name-color":"#14CC1F","alt-1-border-thickness":"false","alt-2-shadows":"false","alt-1-logo-size":"-2","global-lock-active":"false","alt-4-info":"","alt-1-info-2":"","alt-1-shadows":"false","alt-1-name-2":"","alt-4-logo-9":"","alt-2-style-color-1":"#6300E7","alt-2-logo-size":"-2","alt-3-name-color":"#F2F2F2","alt-1-info":"Professional Services Consultant","alt-1-line-spacing":"1","alt-3-line-spacing":"1","alt-4-lock-active":"true","alt-2-info":"Professional Services Consultant","alt-2-name":"John Doe","alt-1-style-color-2":"rgba(59,59,59,0)","alt-4-margin-v":"1","alt-4-name":"","alt-3-inverse-ratio":"8","alt-1-background":"true","alt-1-name-transform":"true","alt-1-info-1":"","alt-4-logo-default":"../logos/logo_4.png","lower-thirds-switch3":"false","alt-1-oneshot":"true","alt-2-lock-active":"true","alt-3-logo-default":"../logos/logo_3.png","alt-3-style":"2","alt-2-logo-default":"../logos/logo_2.png","lower-thirds-switch4":"false","theme":"dark","alt-4-info-9":"","alt-2-font":"'Open Sans', sans-serif","alt-1-align-center":"false","alt-1-animation-time":"","alt-2-background":"true","alt-4-logo":"false","alt-2-name-transform":"true","sorted":"alt[]=1&alt[]=2&alt[]=3&alt[]=4","alt-4-info-color":"#F2F2F2","set-switch-position":"false","alt-1-align-left":"true","alt-2-margin-h":"22","alt-4-style-color-3":"rgba(213,65,65,0)","alt-3-style-color-3":"rgba(213,65,65,0)","alt-2-align-center":"false","alt-2-corners":"0","alt-1-autotrigger":"false","alt-4-name-9":"","alt-2-style":"2","alt-1-size":"24","alt-1-info-color":"#F2F2F2","alt-2-margin-v":"1"}`

**Comment by DavidP-B** [comment]
Thanks for your detailed comment. We will check and give you an answer as soon as possible.

**Comment by noeal-dac** [comment]
Actually, the LT1 is the correct one. The change in height is due to an adjustment in the shadow mask. I will replicate it in the other LTs. Thanks for notifying us! ;)

**Comment by skjall** [comment]
Hahaha, I never thought that the minority of elements could be the right. Thank you! :)
